# Generated by Django 5.1.1 on 2024-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0020_alter_producto_edad_alter_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='obs',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Observaciones'),
        ),
    ]
